export const minecraftBrazilProducts = [
  {
    name: 'Pedra',
    montlyPrice: 19.99,
    quarterly: 57.59,
    yearly: 218.39,
    link: 'https://cliente.primoshost.com.br/index.php?rp=/store/hospedagem-minecraft/minecraft-2gb',
    description: ['2GB de RAM', '5GB SSD NVME', '1vCPU', 'Tráfego Ilimitado', 'AntiDDos PRO'],
  },
  {
    name: 'Carvão',
    montlyPrice: 39.99,
    quarterly: 115.19,
    yearly: 436.79,
    link: 'https://cliente.primoshost.com.br/index.php?rp=/store/hospedagem-minecraft/minecraft-4gb',
    description: ['4GB de RAM', '15GB SSD NVME', '2vCPU', 'Tráfego Ilimitado', 'AntiDDos PRO'],
  },
  {
    name: 'Ferro',
    montlyPrice: 59.99,
    quarterly: 172.79,
    yearly: 655.15,
    link: 'https://cliente.primoshost.com.br/index.php?rp=/store/hospedagem-minecraft/minecraft-6gb',
    description: ['6GB de RAM', '25GB SSD NVME', '2vCPU', 'Tráfego Ilimitado', 'AntiDDos PRO'],
  },
  {
    name: 'Ouro',
    montlyPrice: 79.99,
    quarterly: 230.38,
    yearly: 873.53,
    link: 'https://cliente.primoshost.com.br/index.php?rp=/store/hospedagem-minecraft/minecraft-8gb',
    description: ['8GB de RAM', '35GB SSD NVME', '3vCPU', 'Tráfego Ilimitado', 'AntiDDos PRO'],
  },
  {
    name: 'Diamante',
    montlyPrice: 99.99,
    quarterly: 287.99,
    yearly: 1091.91,
    link: 'https://cliente.primoshost.com.br/index.php?rp=/store/hospedagem-minecraft/minecraft-10gb',
    description: ['10GB de RAM', '45GB SSD NVME', '3vCPU', 'Tráfego Ilimitado', 'AntiDDos PRO'],
  },
  {
    name: 'Esmeralda',
    montlyPrice: 119.99,
    quarterly: 345.57,
    yearly: 1310.29,
    link: 'https://cliente.primoshost.com.br/index.php?rp=/store/hospedagem-minecraft/minecraft-12gb',
    description: ['12GB de RAM', '60GB SSD NVME', '4vCPU', 'Tráfego Ilimitado', 'AntiDDos PRO'],
  },
];
