export const minecraftBrazilProducts = [
  {
    name: 'Pedra',
    montlyPrice: 19.99,
    montlyChristmasPrice: 16.99,
    quarterly: 57.59,
    quarterlyChristmas: 48.95,
    yearly: 218.39,
    yearlyChristmas: 185.63,
    link: 'https://cliente.primoshost.com.br/index.php?rp=/store/hospedagem-minecraft/minecraft-2gb',
    description: ['2GB de RAM', '5GB SSD NVME', '1vCPU', 'Backup incluso', 'AntiDDos PRO', 'Suporta Java e Bedrock'],
  },
  {
    name: 'Carvão',
    montlyPrice: 39.99,
    montlyChristmasPrice: 34.99,
    quarterly: 115.19,
    quarterlyChristmas: 97.91,
    yearly: 436.79,
    yearlyChristmas: 371.271,
    link: 'https://cliente.primoshost.com.br/index.php?rp=/store/hospedagem-minecraft/minecraft-4gb',
    description: ['4GB de RAM', '15GB SSD NVME', '2vCPU', 'Backup incluso', 'AntiDDos PRO', 'Suporta Java e Bedrock'],
  },
  {
    name: 'Ferro',
    montlyPrice: 59.99,
    montlyChristmasPrice: 51.99,
    quarterly: 172.79,
    quarterlyChristmas: 146.87,
    yearly: 655.15,
    yearlyChristmas: 556.87,
    link: 'https://cliente.primoshost.com.br/index.php?rp=/store/hospedagem-minecraft/minecraft-6gb',
    description: ['6GB de RAM', '25GB SSD NVME', '2vCPU', 'Backup incluso', 'AntiDDos PRO', 'Suporta Java e Bedrock'],
  },
  {
    name: 'Ouro',
    montlyPrice: 79.99,
    montlyChristmasPrice: 67.99,
    quarterly: 230.38,
    quarterlyChristmas: 195.82,
    yearly: 873.53,
    yearlyChristmas: 742.5,
    link: 'https://cliente.primoshost.com.br/index.php?rp=/store/hospedagem-minecraft/minecraft-8gb',
    description: ['8GB de RAM', '35GB SSD NVME', '3vCPU', 'Backup incluso', 'AntiDDos PRO', 'Suporta Java e Bedrock'],
  },
  {
    name: 'Diamante',
    montlyPrice: 99.99,
    montlyChristmasPrice: 84.99,
    quarterly: 287.99,
    quarterlyChristmas: 244.79,
    yearly: 1091.91,
    yearlyChristmas: 928.12,
    link: 'https://cliente.primoshost.com.br/index.php?rp=/store/hospedagem-minecraft/minecraft-10gb',
    description: ['10GB de RAM', '45GB SSD NVME', '3vCPU', 'Backup incluso', 'AntiDDos PRO', 'Suporta Java e Bedrock'],
  },
  {
    name: 'Esmeralda',
    montlyPrice: 119.99,
    montlyChristmasPrice: 101.99,
    quarterly: 345.57,
    quarterlyChristmas: 293.73,
    yearly: 1310.29,
    yearlyChristmas: 1113.74,
    link: 'https://cliente.primoshost.com.br/index.php?rp=/store/hospedagem-minecraft/minecraft-12gb',
    description: ['12GB de RAM', '60GB SSD NVME', '4vCPU', 'Backup incluso', 'AntiDDos PRO', 'Suporta Java e Bedrock'],
  },
];

export const palworldBrazilProducts = [
  {
    name: 'Inicial',
    montlyPrice: 91.45,
    quarterly: 263.39,
    yearly: 998.65,
    link: 'https://cliente.primoshost.com.br/index.php?rp=/store/hospedagem-palworld/hospedagem-palworld-6gb',
    description: ['Ryzen 9 5950x', '6GB de RAM', '15GB SSD NVME', '2vCPU', 'Tráfego Ilimitado', 'AntiDDos PRO'],
  },
  {
    name: 'Intermediário',
    montlyPrice: 182.9,
    quarterly: 526.76,
    yearly: 1997.3,
    link: 'https://cliente.primoshost.com.br/index.php?rp=/store/hospedagem-palworld/palworld-12gb',
    description: ['Ryzen 9 5950x', '12GB de RAM', '25GB SSD NVME', '3vCPU', 'Tráfego Ilimitado', 'AntiDDos PRO'],
  },
  {
    name: 'Avançado',
    montlyPrice: 243.87,
    quarterly: 702.35,
    yearly: 2663.07,
    link: 'https://cliente.primoshost.com.br/index.php?rp=/store/hospedagem-palworld/palworld-16gb',
    description: ['Ryzen 9 5950x', '16GB de RAM', '30GB SSD NVME', '4vCPU', 'Tráfego Ilimitado', 'AntiDDos PRO'],
  },
];

export const vpsGamingBrazilProducts = [
  {
    processor: 'Ryzen 9 5950x',
    cores: '2vCPU',
    ram: '2GB',
    disk: '40GB',
    montlyPrice: 55.05,
    quarterly: 160.5,
    yearly: 618.59,
    link: 'https://cliente.primoshost.com.br/index.php?rp=/store/vps-gaming/vps-gaming-2gb',
  },
  {
    processor: 'Ryzen 9 5950x',
    cores: '2vCPU',
    ram: '4GB',
    disk: '60GB',
    montlyPrice: 94.15,
    quarterly: 273.0,
    yearly: 1045.17,
    link: 'https://cliente.primoshost.com.br/index.php?rp=/store/vps-gaming/vps-gaming-4gb',
  },
  {
    processor: 'Ryzen 9 5950x',
    cores: '3vCPU',
    ram: '6GB',
    disk: '70GB',
    montlyPrice: 133.2,
    quarterly: 385.52,
    yearly: 1471.75,
    link: 'https://cliente.primoshost.com.br/index.php?rp=/store/vps-gaming/vps-gaming-6gb',
  },
  {
    processor: 'Ryzen 9 5950x',
    cores: '3vCPU',
    ram: '8GB',
    disk: '90GB',
    montlyPrice: 172.29,
    quarterly: 498.02,
    yearly: 1898.34,
    link: 'https://cliente.primoshost.com.br/index.php?rp=/store/vps-gaming/vps-gaming-8gb',
  },
  {
    processor: 'Ryzen 9 5950x',
    cores: '4vCPU',
    ram: '10GB',
    disk: '100GB',
    montlyPrice: 211.32,
    quarterly: 610.55,
    yearly: 2324.92,
    link: 'https://cliente.primoshost.com.br/index.php?rp=/store/vps-gaming/vps-gaming-10gb',
  },
  {
    processor: 'Ryzen 9 5950x',
    cores: '4vCPU',
    ram: '12GB',
    disk: '120GB',
    montlyPrice: 250.39,
    quarterly: 723.03,
    yearly: 2751.51,
    link: 'https://cliente.primoshost.com.br/index.php?rp=/store/vps-gaming/vps-gaming-12gb',
  },
];
